before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/series-cleanup
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: build/package/Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}-amd64
  - goos: linux
    goarch: arm64
    dockerfile: build/package/Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}-arm64

docker_manifests:
- name_template: ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}
  image_templates:
    - ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}-amd64
    - ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}-arm64
- name_template: ghcr.io/bjw-s/{{ .ProjectName }}:latest
  image_templates:
    - ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}-amd64
    - ghcr.io/bjw-s/{{ .ProjectName }}:{{ .Tag }}-arm64
