name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"

      - uses: actions/cache@v2
        with:
          path: /home/runner/go/pkg/mod
          key: go-mod

      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-sign
