name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19.1"

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot --skip-sign
