---
name: Docker Image CI
on:
  workflow_dispatch:

  release:
    types: [ published ]

jobs:
  hadolint:
    name: Run hadolint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: hadolint
      uses: reviewdog/action-hadolint@v1.17.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        filter_mode: diff_context
        fail_on_error: true

  build:
    runs-on: ubuntu-latest
    needs:
    - hadolint
    env:
      IMAGE_NAMESPACE: ${{ github.repository_owner }}
      IMAGE_NAME: series-cleanup
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the version
      id: version
      run: |
        TAG_NAME="${{ github.event.release.tag_name }}"
        TAG_NAME="${TAG_NAME#"v"}"
        echo "::set-output name=tag::${TAG_NAME}"

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.CR_PAT }}

    # Install and configure Buildx
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: amd64
        file: ./build/package/Dockerfile
        push: true
        tags: |
          ghcr.io/${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest
          ghcr.io/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${{steps.version.outputs.tag}}
