---
name: docker
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * 0'
jobs:
  docker:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: ghcr.io/bjw-s/series-cleanup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build container image
        run: |
          docker build \
            -t "${IMAGE_NAME}:latest" \
            -t "${IMAGE_NAME}:$(date '+%Y.%m.%d')" \
            -f build/package/Dockerfile .
      - name: Push container image
        run: |
          docker push "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:$(date '+%Y.%m.%d')"
