---
name: Docker Image CI
on:
  workflow_dispatch:

  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the version
      id: version
      run: |
        TAG_NAME="${{ github.event.release.tag_name }}"
        TAG_NAME="${TAG_NAME#"v"}"
        echo "::set-output name=tag::${TAG_NAME}"

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.CR_PAT }}

    # Install and configure Buildx
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: amd64
        file: ./build/package/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/series-cleanup:latest
          ghcr.io/${{ github.repository_owner }}/series-cleanup:${{steps.version.outputs.tag}}
