---
name: Release

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rolling.yaml"
      - ".dockerignore"
      - "dist/docker/Dockerfile"
      - "**.go"
      - "go.*"

env:
  # Registry where the image is stored
  IMAGE_REGISTRY: ghcr.io

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get bjw-s-bot token
        id: get-app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.BJWS_APP_ID }}
          private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get-app-token.outputs.token }}

      - name: Prepare environment vars
        id: prep
        run: |
          echo "version=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dist/docker/Dockerfile
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/series-cleanup:rolling
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/series-cleanup:${{ steps.prep.outputs.version }}
          labels: |
            org.opencontainers.image.version="${{ steps.prep.outputs.version }}"
          platforms: linux/amd64,linux/arm64
          push: true
